export const CREATE_TASK = "CREATE_TASK";
export const RETRIEVE_TASKS_BY_ID = "RETRIEVE_TASKS_BY_ID";
export const RETRIEVE_TASKS = "RETRIEVE_TASKS";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
